# Introduction to NumPy

## Instructions:
* Go through the notebook and complete the tasks. 
* Make sure you understand the examples given. If you need help, refer to the documentation links provided or go to the discussion forum. 
* Save your notebooks when you are done.

Note that we use the import keyword to import modules and libraries in Python. You can find out more about this <a href="https://docs.python.org/3/tutorial/modules.html">here</a>.




In [1]:
import numpy as np

## 1 NumPy arrays

NumPy n-dimensional arrays (referred to as ndarrays are a fundamental structure for ML in Python.

### 1.1 Usage examples

To create a NumPy array from list:

    data1D = [6, 7, 8]
    data1DnD = np.array(data1D)
    print(data1D)
    print(data1DnD)

To print useful properties of our array:

    print(data1DnD.shape)
    print(data1DnD.ndim)
    print(data1DnD.dtype)

To change the type of elements:

    data1DnD_float = data1DnD.astype(np.float)
    data1DnD_string = data1DnD.astype(np.string_)

For array indexing:

    print(a[0])   #return the first element of ndarray a
    print(a[:])   #return all the elements of ndarray a
    print(a[-1])  #return the last element of ndarray a
    print(a[:-1]) #return everything up to the last element
    print(a[:-2]) #return everything up to the second last element
    print(a[-2])  #return the second last element

There are various ways of creating an ndarray:

    a = np.array([1, 2, 3])
    b = np.zeros((1,5))              # Create an array of all zeros
    c = np.ones((1,5))               # Create an array of all ones
    d = np.full((1,5), 7)            # Create an array filled with value 7
    e = np.random.random((1,4))      # Create an array filled with random values
    f = np.eye(3)                    # Create a 3x3 identity matrix (2D array)
    g = np.ones((3,3,3))             # 3-Dimensional array

As the name suggests, an n-dimensional array can be generalised to multiple dimensions:

    A=np.array([ [1,2], [3,4] ])     # Create a 2-D array (Matrix)
    print(A[0,1])                    # return the element on first column, second row (0,1)=2
                                     # array indexing works as above

We can reshape a vector (for example, ```v=[v1,v2,…,vN]```) to a matrix of ```N1 x N2``` dimensions (where ```N1xN2 = N```). This is particularly useful for plotting images.  As an example using numpy’s reshape method:

    A = np.array([1,2,3,4,5,6])  # a 1D array 
    B = np.reshape( A, [2,3] ) # reshape as a 2D array with 2 rows and 3 columns
    print(B)
 
**Task 1:**
Go through the examples above, pasting the code given in the empty cell below and verifying the results. 
Make sure you understand what this basic code does. You can find some NumPy documentation <a href="http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html">here</a>.

In [2]:
# np.float has been deprecated

# Creating a 1D array from a list
data1D = [6, 7, 8]
data1DnD = np.array(data1D)
print("Original List:", data1D)
print("NumPy Array:", data1DnD)

# Printing useful properties of the array
print("Shape:", data1DnD.shape)
print("Dimensions:", data1DnD.ndim)
print("Data Type:", data1DnD.dtype)

# Changing the type of elements
data1DnD_float = data1DnD.astype(float)  # Use float instead of np.float
data1DnD_string = data1DnD.astype(np.string_)

print("Array with float type:", data1DnD_float)
print("Array with string type:", data1DnD_string)

# Array indexing examples
print("First element:", data1DnD[0])      # Return the first element of ndarray
print("All elements:", data1DnD[:])       # Return all the elements of ndarray
print("Last element:", data1DnD[-1])      # Return the last element
print("All elements except the last:", data1DnD[:-1])  # Return everything up to the last element
print("All elements except the last two:", data1DnD[:-2])  # Return everything up to the second last element
print("Second last element:", data1DnD[-2])  # Return the second last element

# Ways to create an ndarray
a = np.array([1, 2, 3])           # 1D array
b = np.zeros((1, 5))              # Array of all zeros
c = np.ones((1, 5))               # Array of all ones
d = np.full((1, 5), 7)            # Array filled with value 7
e = np.random.random((1, 4))      # Array filled with random values
f = np.eye(3)                    # 3x3 identity matrix (2D array)
g = np.ones((3, 3, 3))             # 3D array

print("Array a:", a)
print("Array b (zeros):", b)
print("Array c (ones):", c)
print("Array d (filled with 7):", d)
print("Array e (random values):", e)
print("Identity Matrix f:", f)
print("3D Array g:", g)

# Creating a 2D array (Matrix)
A = np.array([[1, 2], [3, 4]])     # 2D array (matrix)
print("Element at position (0, 1):", A[0, 1])  # Return the element at first row, second column (0,1)=2

# Reshaping a 1D array to a 2D array
B = np.array([1, 2, 3, 4, 5, 6])   # A 1D array 
reshaped_B = np.reshape(B, [2, 3]) # Reshape as a 2D array with 2 rows and 3 columns
print("Reshaped 2D array B:", reshaped_B)

Original List: [6, 7, 8]
NumPy Array: [6 7 8]
Shape: (3,)
Dimensions: 1
Data Type: int32
Array with float type: [6. 7. 8.]
Array with string type: [b'6' b'7' b'8']
First element: 6
All elements: [6 7 8]
Last element: 8
All elements except the last: [6 7]
All elements except the last two: [6]
Second last element: 7
Array a: [1 2 3]
Array b (zeros): [[0. 0. 0. 0. 0.]]
Array c (ones): [[1. 1. 1. 1. 1.]]
Array d (filled with 7): [[7 7 7 7 7]]
Array e (random values): [[0.09210091 0.23051248 0.55919379 0.76171093]]
Identity Matrix f: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3D Array g: [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
Element at position (0, 1): 2
Reshaped 2D array B: [[1 2 3]
 [4 5 6]]


**Task 2:**
In the empty cell below, create an np array called ```L``` consisting of 15 random elements.


In [3]:
# code here
L=np.random.random(15)
print(L)

[0.07188225 0.37674224 0.14361376 0.91012979 0.10671636 0.02906983
 0.05615615 0.42705692 0.47204669 0.76515662 0.72587248 0.17425593
 0.11506647 0.81088182 0.16268537]


**Task 3:**
Reshape the array ```L``` to a matrix ```A``` that has 5 rows and 3 columns. Print the matrix to verify the result.


In [4]:
# code here
A=L.reshape(5,3)
print(A)

[[0.07188225 0.37674224 0.14361376]
 [0.91012979 0.10671636 0.02906983]
 [0.05615615 0.42705692 0.47204669]
 [0.76515662 0.72587248 0.17425593]
 [0.11506647 0.81088182 0.16268537]]


**Task 4:**
Reshape matrix ```A``` to a matrix ```B``` that has 3 rows and 5 columns. Then, print the elements in row 0 and 1 only.


In [5]:
# code here
B=A.reshape(3,5)
print(B)
print(B[0:2,:])

[[0.07188225 0.37674224 0.14361376 0.91012979 0.10671636]
 [0.02906983 0.05615615 0.42705692 0.47204669 0.76515662]
 [0.72587248 0.17425593 0.11506647 0.81088182 0.16268537]]
[[0.07188225 0.37674224 0.14361376 0.91012979 0.10671636]
 [0.02906983 0.05615615 0.42705692 0.47204669 0.76515662]]


**Task: 5**
Print all elements of ```B``` that are in row 0 and 2 <b>and</b> column 1.


In [6]:
# code here
print(B[ [0,2], 1])

[0.37674224 0.17425593]


**Task 6:**
Print all elements of ```A``` that are in the last row (see the ```[-1]``` notation above) and second to last column.


In [7]:
# code here
print(B[ [-1], -2])

[0.81088182]


**Task 7:**
Given the array ```Y``` below, find all indices in the array that are equal to the value 1. Use the NumPy function where to do that. Your final output should look like this: ```[1, 3, 4, 7]```.
You can find some useful documentation to help you with this <a href="https://numpy.org/doc/stable/reference/generated/numpy.where.html">here</a>.


In [8]:
Y=np.array([0, 1, 0, 1,1, 2,0,1,0])
# code here
np.where(Y==1)

(array([1, 3, 4, 7], dtype=int64),)

**Task 8:**
Split the array ```Y``` defined above into three arrays by using the NumPy function ```array_split```. Print to verify.
You can find some useful documentation to help you with this <a href="https://numpy.org/doc/stable/reference/generated/numpy.array_split.html">here</a>.


In [9]:
# code here
np.array_split(Y,3)

[array([0, 1, 0]), array([1, 1, 2]), array([0, 1, 0])]

**Task 9:**
Given the array ```D``` defined below, find the indices that sort the array. Use the NumPy function ```argsort``` in order to do so. Subsequently, print the sorted array. 
The final output should look like this: ```[ 0 1 2 5 9 10 20]```.


In [10]:
D=np.array([10,5,2,9,20,0,1])
# code here
idx=np.argsort(D)
print(D[idx])

[ 0  1  2  5  9 10 20]


**Task 10:**
Create two random 2x2 matrices ```X``` and ```Y``` (2 rows, 2 columns). Use the NumPy function ```concatenate``` in order to concatenate them and create a matrix ```Z``` that has dimensions 4x2 and a matrix ```W``` that has dimensions 2x4.
You can find some useful documentation to help you with this <a href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.concatenate.html">here</a>.


In [11]:
# code here
X=np.random.random((2,2))
Y=np.random.random((2,2))

Z=np.concatenate((X,Y),axis=0)
W=np.concatenate((X,Y),axis=1)
print(Z)
print(W)

[[0.93005674 0.18921789]
 [0.37513207 0.92947772]
 [0.62977674 0.23198979]
 [0.29080048 0.17609419]]
[[0.93005674 0.18921789 0.62977674 0.23198979]
 [0.37513207 0.92947772 0.29080048 0.17609419]]


**Task 11:**
Create the same matrices ```Z2=Z``` and ```W2=W``` (where ```Z``` and ```W``` are as defined above), but this time use the NumPy functions ```hstack``` and ```vstack```.

You can find some useful documentation to help you with ```hstack``` <a href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.hstack.html#numpy.hstack">here</a> and ```vstack``` <a href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vstack.html#numpy.vstack">here</a>.


In [12]:
# code here
Z2 = np.vstack((X,Y))
W2 = np.hstack((X,Y))
print(Z2)
print(W2)

[[0.93005674 0.18921789]
 [0.37513207 0.92947772]
 [0.62977674 0.23198979]
 [0.29080048 0.17609419]]
[[0.93005674 0.18921789 0.62977674 0.23198979]
 [0.37513207 0.92947772 0.29080048 0.17609419]]
